import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";

type Language = "fr" | "ar" | "en";
type Currency = "EUR" | "MAD";

interface PreferencesContextType {
  language: Language;
  currency: Currency;
  locale: string;
  setLanguage: (language: Language) => void;
  setCurrency: (currency: Currency) => void;
  formatMoney: (amountInEur: number) => string;
  formatDate: (date: string | number | Date, options?: Intl.DateTimeFormatOptions) => string;
  t: (key: string) => string;
}

const EUR_TO_MAD = 11;

const labels: Record<Language, Record<string, string>> = {
  fr: {
    language: "Langue",
    currency: "Devise",
    clientSpace: "ESPACE CLIENT",
    adminSpace: "ADMINISTRATION",
    home: "Accueil",
    offers: "Offres",
    reservations: "Réservations",
    payment: "Paiement",
    tickets: "Billets",
    profile: "Profil",
    adminProfile: "Profil admin",
    dashboard: "Dashboard",
    logout: "Se déconnecter",
    loading: "Chargement...",
    save: "Enregistrer",
    cancel: "Annuler",
    close: "Fermer",
    delete: "Supprimer",
    edit: "Modifier",
    confirm: "Confirmer",
    print: "Imprimer",
    download: "Télécharger",
    requiredFields: "Veuillez remplir tous les champs",
    fourDigitsRequired: "Veuillez saisir exactement 4 chiffres",
    addError: "Erreur lors de l'ajout",
    updateError: "Erreur lors de la mise à jour",
    passwordMismatch: "Les mots de passe ne correspondent pas",
    passwordRule: "Le mot de passe doit contenir au moins 6 caractères, une lettre et un chiffre",
    loginError: "Email ou mot de passe incorrect",
    registerError: "Erreur lors de l'inscription",
    landingBadge: "SafarGo Travel",
    landingTitle: "Voyages organisés, Omra, Hajj, événements et transport",
    landingSubtitle: "Découvrez les offres, comparez les prix et connectez-vous pour réserver en quelques clics.",
    login: "Connexion",
    signup: "Créer un compte",
    mySpace: "Mon espace",
    landingStatOffers: "offres organisées",
    landingStatSupport: "support local",
    landingStatSecure: "réservation sécurisée",
    landingSelection: "Sélection SafarGo",
    popularOffers: "Offres populaires",
    bookNow: "Réserver maintenant",
    from: "dès",
    authTagline: "Voyage organisé",
    authTitle: "Réservez vos voyages, billets et packages en quelques clics.",
    authSubtitle: "SafarGo réunit destinations, Omra, Hajj, événements et transport dans une seule expérience simple.",
    authOffers: "+25 offres",
    authSecure: "Paiement sécurisé",
    authSupport: "Support local",
    welcome: "Bienvenue",
    loginTitle: "Connexion",
    registerTitle: "Créer un compte",
    loginHelp: "Connectez-vous pour gérer vos réservations.",
    registerHelp: "Créez votre espace client SafarGo.",
    email: "Email",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    enterEmail: "Veuillez saisir votre email",
    verificationCode: "Code de vérification",
    emailNotFound: "Aucun compte avec cet email",
    invalidCode: "Code incorrect",
    enterNewPassword: "Veuillez saisir un nouveau mot de passe",
    passwordUpdated: "Mot de passe mis à jour avec succès !",
    resetError: "Erreur lors de la réinitialisation",
    resetHero: "RÉINITIALISEZ VOTRE MOT DE PASSE",
    travelAgain: "ET VOYAGEZ À NOUVEAU",
    yourEmail: "Votre email",
    sending: "Envoi...",
    sendCode: "Envoyer le code",
    codeSentTo: "Code envoyé à",
    verifyCode: "Vérifier le code",
    reset: "Réinitialiser",
    backToLogin: "Retour à la connexion",
    signIn: "SE CONNECTER",
    signingIn: "CONNEXION...",
    createAccount: "CRÉER MON COMPTE",
    creatingAccount: "CRÉATION...",
    or: "OU",
    continueGoogle: "Continuer avec Google",
    continueApple: "Continuer avec Apple",
    continueMicrosoft: "Continuer avec Microsoft",
    fullName: "Nom complet",
    phoneOptional: "Téléphone (optionnel)",
    passwordRuleShort: "Mot de passe (lettres + chiffres)",
    confirmPassword: "Confirmer le mot de passe",
    hello: "Bonjour",
    homeSubtitle: "Bienvenue sur SafarGo — prêt pour votre prochain voyage ?",
    marketingTitle: "Découvrez le monde avec une réservation simple et rapide",
    marketingSubtitle: "Voyages, Omra, Hajj, événements et transport au même endroit.",
    exploreOffers: "Explorer les offres",
    confirmedTrips: "Voyages confirmés",
    pending: "En attente",
    totalSpent: "Total dépensé",
    popularDestinations: "Destinations populaires",
    seeAll: "Voir tout",
    upcomingTrips: "Prochains voyages",
    noUpcomingTrips: "Aucun voyage prévu.",
    quickAccess: "Accès rapide",
    exploreTrips: "Explorer les voyages",
    myReservations: "Mes réservations",
    payments: "Paiements",
    documents: "Billets & factures",
    myProfile: "Mon profil",
    departure: "Départ",
    passengers: "passager(s)",
    confirmed: "Confirmée",
    cancelled: "Annulée",
    offersTitle: "Voyages & Offres",
    offersSubtitle: "Découvrez nos meilleures destinations",
    searchDestination: "Rechercher une destination...",
    transportMode: "Moyen de transport",
    maxBudget: "Budget max",
    loadingOffers: "Chargement des offres...",
    noOffers: "Aucune offre trouvée.",
    seatsLeft: "places restantes",
    perPerson: "/pers.",
    days: "jours",
    bookOffer: "Réserver maintenant",
    startingFrom: "À partir de",
    person: "par personne",
    rating: "Note",
    seats: "Places",
    available: "disponibles",
    transport: "Transport",
    nextDeparture: "Prochain départ",
    onRequest: "Sur demande",
    route: "Trajet",
    eventDate: "Date événement",
    continueBooking: "Continuer la réservation",
    bookingFor: "Réserver",
    departureDate: "Date de départ",
    passengerCount: "Nombre de passagers",
    total: "Total",
    inProgress: "En cours...",
    reservationSuccess: "Réservation créée avec succès !",
    reservationError: "Erreur lors de la réservation",
    reservationsTitle: "Mes Réservations",
    reservationsSubtitle: "Gérez tous vos voyages réservés",
    newReservation: "+ Nouvelle réservation",
    activeTotal: "Total actif",
    all: "Toutes",
    noReservation: "Aucune réservation.",
    photos: "photos",
    pay: "Payer",
    cancelReservation: "Annuler",
    deleteReservationConfirm: "Supprimer définitivement cette réservation ?",
    cancelReservationConfirm: "Annuler cette réservation ?",
    paymentSuccess: "Paiement réussi !",
    paymentError: "Erreur de paiement",
    payTitle: "Payer",
    amount: "Montant",
    noCardForPayment: "Aucune carte enregistrée. Ajoutez-en une dans Paiements.",
    goToPayments: "Aller aux paiements",
    chooseCard: "Choisir une carte",
    processing: "Traitement...",
    confirmPayment: "Confirmer le paiement",
    paymentsTitle: "Paiements",
    paymentsSubtitle: "Gérez vos cartes et consultez l'historique",
    securePayment: "Paiement sécurisé",
    services: "Services",
    contact: "Contact",
    footerText: "SafarGo simplifie vos voyages, billets, packages religieux, événements et transports avec une expérience claire et rapide.",
    addCard: "Ajouter une carte",
    savedCards: "Cartes enregistrées",
    successfulPayments: "Paiements réussis",
    totalPaid: "Total payé",
    myCards: "Mes cartes",
    noSavedCards: "Aucune carte enregistrée.",
    default: "Par défaut",
    savedCardHint: "Carte enregistrée pour vos prochaines réservations",
    paymentHistory: "Historique des paiements",
    noPayments: "Aucun paiement effectué.",
    description: "Description",
    method: "Méthode",
    date: "Date",
    status: "Statut",
    paidStatus: "Réussi",
    failedStatus: "Échoué",
    refundedStatus: "Remboursé",
    cardType: "Type de carte",
    lastFour: "4 derniers chiffres",
    expiryPlaceholder: "Date d'expiration (ex: 12/28)",
    cardHolder: "Titulaire de la carte",
    saving: "Enregistrement...",
    deleteCardConfirm: "Supprimer cette carte ?",
    docsTitle: "Billets & Factures",
    docsSubtitle: "Consultez, imprimez et téléchargez vos documents",
    confirmedTickets: "Billets confirmés",
    generatedInvoices: "Factures générées",
    totalInvoiced: "Total facturé",
    ticketsTab: "Billets",
    invoicesTab: "Factures",
    loadingDocuments: "Chargement des documents...",
    noTicket: "Aucun billet confirmé.",
    noInvoice: "Aucune facture disponible.",
    ticket: "Billet",
    invoice: "Facture",
    paid: "PAYÉ",
    profileAdmin: "Profil admin",
    profileMine: "Mon profil",
    adminRole: "Administrateur",
    clientRole: "Client SafarGo",
    editProfile: "Modifier le profil",
    managedOffers: "Offres gérées",
    clientReservations: "Réservations clients",
    clients: "Clients",
    adminArea: "Espace administrateur",
    adminAreaText: "Votre compte donne accès à la gestion des offres, des clients et des réservations.",
    openDashboard: "Ouvrir le dashboard",
    changePhoto: "Changer la photo",
    role: "Rôle",
    phone: "Téléphone",
    deleteAccount: "Supprimer le compte",
    deleteAccountConfirm: "Supprimer votre compte définitivement ?",
    addPhotoError: "Erreur lors de l'ajout de la photo",
    country: "Pays",
    changePassword: "Changer le mot de passe",
    oldPassword: "Ancien mot de passe",
    newPassword: "Nouveau mot de passe",
    paymentMethods: "Moyens de paiement",
    paymentMethodsText: "Gérez vos cartes bancaires et consultez l'historique de vos paiements.",
    manageCards: "Gérer mes cartes",
    promo: "Promo",
    promoOmra: "Promotion Omra Ramadan - jusqu'à 15% de réduction",
    promoEvents: "Billets événements disponibles avec confirmation rapide",
    promoShuttle: "Navette Casablanca - Marrakech à partir de",
    promoHajj: "Packages Hajj avec accompagnement complet",
    promoTransport: "Offres transport: bus, avion, train et bateau",
    catAll: "Tous",
    catTrips: "Voyages",
    catEvents: "Événements",
    catHajj: "Hajj",
    catOmra: "Omra",
    catTransport: "Transport",
    catEurope: "Europe",
    catAsia: "Asie",
    catAfrica: "Afrique",
    catAmericas: "Amériques",
    catMiddleEast: "Moyen-Orient",
    catIndianOcean: "Océan Indien",
    transportAll: "Tous",
    plane: "Avion",
    bus: "Bus",
    train: "Train",
    boat: "Bateau",
    car: "Voiture",
    accordingProgram: "Selon programme",
    program: "Programme",
    adminLoginError: "Connexion admin impossible",
    adminAccess: "Accès administrateur",
    adminLogin: "Connexion admin",
    loggedAsClient: "Connecté comme client",
    adminLoginHelp: "Entrez les identifiants administrateur pour passer au tableau de bord admin.",
    adminEmail: "Email admin",
    adminPassword: "Mot de passe admin",
    checking: "Vérification...",
    enterAsAdmin: "Entrer comme admin",
    notFound: "Page introuvable.",
    adminContent: "Gestion du contenu SafarGo",
    users: "Utilisateurs",
    destinations: "Destinations",
    addTrip: "Ajouter un voyage",
    editTrip: "Modifier le voyage",
    destination: "Destination",
    price: "Prix",
    duration: "Durée",
    actions: "Actions",
    account: "Compte",
    registeredAt: "Inscrit le",
    userRole: "Utilisateur",
    active: "Activé",
    inactive: "Désactivé",
    blocked: "Bloqué",
    removeAdmin: "Retirer admin",
    makeAdmin: "Rendre admin",
    client: "Client",
    editUser: "Modifier l'utilisateur",
    accountActive: "Compte activé",
    offerType: "Type d'offre",
    photoGallery: "Galerie photos",
    imageUrlPerLine: "Une URL d'image par ligne",
    create: "Créer",
    confirmDelete: "Confirmer la suppression",
    deleteTripText: "Voulez-vous vraiment supprimer ce voyage ? Cette action est irréversible.",
    deleteUser: "Supprimer l'utilisateur",
    deleteUserText: "Voulez-vous vraiment supprimer cet utilisateur ? Ses réservations, paiements et cartes seront supprimés aussi.",
    back: "Retour",
    deleteReservation: "Supprimer la réservation",
  },
  ar: {
    language: "اللغة",
    currency: "العملة",
    clientSpace: "فضاء الزبون",
    adminSpace: "الإدارة",
    home: "الرئيسية",
    offers: "العروض",
    reservations: "الحجوزات",
    payment: "الدفع",
    tickets: "التذاكر",
    profile: "الملف الشخصي",
    adminProfile: "ملف المدير",
    dashboard: "لوحة التحكم",
    logout: "تسجيل الخروج",
    loading: "جار التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    close: "إغلاق",
    delete: "حذف",
    edit: "تعديل",
    confirm: "تأكيد",
    print: "طباعة",
    download: "تحميل",
    requiredFields: "يرجى ملء جميع الحقول",
    fourDigitsRequired: "يرجى إدخال 4 أرقام بالضبط",
    addError: "حدث خطأ أثناء الإضافة",
    updateError: "حدث خطأ أثناء التحديث",
    passwordMismatch: "كلمتا المرور غير متطابقتين",
    passwordRule: "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل، وحرف ورقم",
    loginError: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    registerError: "حدث خطأ أثناء التسجيل",
    landingBadge: "SafarGo Travel",
    landingTitle: "رحلات منظمة، عمرة، حج، فعاليات وتنقل",
    landingSubtitle: "اكتشف العروض، قارن الأسعار، ثم سجل الدخول للحجز بسهولة.",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    mySpace: "مساحتي",
    landingStatOffers: "عرض منظم",
    landingStatSupport: "دعم محلي",
    landingStatSecure: "حجز آمن",
    landingSelection: "اختيار SafarGo",
    popularOffers: "العروض الشائعة",
    bookNow: "احجز الآن",
    from: "ابتداء من",
    authTagline: "رحلات منظمة",
    authTitle: "احجز رحلاتك وتذاكرك وباقاتك في دقائق.",
    authSubtitle: "SafarGo يجمع الرحلات، العمرة، الحج، الفعاليات والتنقل في تجربة واحدة سهلة.",
    authOffers: "+25 عرض",
    authSecure: "دفع آمن",
    authSupport: "دعم محلي",
    welcome: "مرحبا",
    loginTitle: "تسجيل الدخول",
    registerTitle: "إنشاء حساب",
    loginHelp: "سجل الدخول لتدبير حجوزاتك.",
    registerHelp: "أنشئ مساحة الزبون الخاصة بك في SafarGo.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    enterEmail: "يرجى إدخال بريدك الإلكتروني",
    verificationCode: "رمز التحقق",
    emailNotFound: "لا يوجد حساب بهذا البريد الإلكتروني",
    invalidCode: "الرمز غير صحيح",
    enterNewPassword: "يرجى إدخال كلمة مرور جديدة",
    passwordUpdated: "تم تحديث كلمة المرور بنجاح!",
    resetError: "حدث خطأ أثناء إعادة التعيين",
    resetHero: "أعد تعيين كلمة المرور",
    travelAgain: "وسافر من جديد",
    yourEmail: "بريدك الإلكتروني",
    sending: "جار الإرسال...",
    sendCode: "إرسال الرمز",
    codeSentTo: "تم إرسال الرمز إلى",
    verifyCode: "التحقق من الرمز",
    reset: "إعادة التعيين",
    backToLogin: "الرجوع إلى تسجيل الدخول",
    signIn: "تسجيل الدخول",
    signingIn: "جار تسجيل الدخول...",
    createAccount: "إنشاء حسابي",
    creatingAccount: "جار الإنشاء...",
    or: "أو",
    continueGoogle: "المتابعة عبر Google",
    continueApple: "المتابعة عبر Apple",
    continueMicrosoft: "المتابعة عبر Microsoft",
    fullName: "الاسم الكامل",
    phoneOptional: "الهاتف (اختياري)",
    passwordRuleShort: "كلمة المرور (حروف + أرقام)",
    confirmPassword: "تأكيد كلمة المرور",
    hello: "مرحبا",
    homeSubtitle: "مرحبا بك في SafarGo، مستعد لرحلتك القادمة؟",
    marketingTitle: "اكتشف العالم بحجز بسيط وسريع",
    marketingSubtitle: "رحلات، عمرة، حج، فعاليات وتنقل في مكان واحد.",
    exploreOffers: "استكشف العروض",
    confirmedTrips: "رحلات مؤكدة",
    pending: "قيد الانتظار",
    totalSpent: "إجمالي المصروف",
    popularDestinations: "وجهات شائعة",
    seeAll: "عرض الكل",
    upcomingTrips: "الرحلات القادمة",
    noUpcomingTrips: "لا توجد رحلة مبرمجة.",
    quickAccess: "وصول سريع",
    exploreTrips: "استكشف الرحلات",
    myReservations: "حجوزاتي",
    payments: "المدفوعات",
    documents: "التذاكر والفواتير",
    myProfile: "ملفي الشخصي",
    departure: "المغادرة",
    passengers: "مسافر",
    confirmed: "مؤكدة",
    cancelled: "ملغاة",
    offersTitle: "الرحلات والعروض",
    offersSubtitle: "اكتشف أفضل وجهاتنا",
    searchDestination: "ابحث عن وجهة...",
    transportMode: "وسيلة النقل",
    maxBudget: "الميزانية القصوى",
    loadingOffers: "جار تحميل العروض...",
    noOffers: "لم يتم العثور على عروض.",
    seatsLeft: "أماكن متبقية",
    perPerson: "/للشخص",
    days: "أيام",
    bookOffer: "احجز الآن",
    startingFrom: "ابتداء من",
    person: "للشخص",
    rating: "التقييم",
    seats: "الأماكن",
    available: "متاحة",
    transport: "النقل",
    nextDeparture: "أقرب انطلاق",
    onRequest: "حسب الطلب",
    route: "المسار",
    eventDate: "تاريخ الفعالية",
    continueBooking: "متابعة الحجز",
    bookingFor: "حجز",
    departureDate: "تاريخ الانطلاق",
    passengerCount: "عدد المسافرين",
    total: "المجموع",
    inProgress: "جار المعالجة...",
    reservationSuccess: "تم إنشاء الحجز بنجاح!",
    reservationError: "حدث خطأ أثناء الحجز",
    reservationsTitle: "حجوزاتي",
    reservationsSubtitle: "دبر جميع رحلاتك المحجوزة",
    newReservation: "+ حجز جديد",
    activeTotal: "المجموع النشط",
    all: "الكل",
    noReservation: "لا توجد حجوزات.",
    photos: "صور",
    pay: "دفع",
    cancelReservation: "إلغاء",
    deleteReservationConfirm: "حذف هذا الحجز نهائيا؟",
    cancelReservationConfirm: "إلغاء هذا الحجز؟",
    paymentSuccess: "تم الدفع بنجاح!",
    paymentError: "خطأ في الدفع",
    payTitle: "دفع",
    amount: "المبلغ",
    noCardForPayment: "لا توجد بطاقة محفوظة. أضف واحدة في صفحة المدفوعات.",
    goToPayments: "الذهاب إلى المدفوعات",
    chooseCard: "اختر بطاقة",
    processing: "جار المعالجة...",
    confirmPayment: "تأكيد الدفع",
    paymentsTitle: "المدفوعات",
    paymentsSubtitle: "دبر بطاقاتك واطلع على سجل المدفوعات",
    securePayment: "دفع آمن",
    services: "الخدمات",
    contact: "تواصل",
    footerText: "SafarGo يسهل رحلاتك وتذاكرك والباقات الدينية والفعاليات والتنقل بتجربة واضحة وسريعة.",
    addCard: "إضافة بطاقة",
    savedCards: "البطاقات المحفوظة",
    successfulPayments: "مدفوعات ناجحة",
    totalPaid: "إجمالي المدفوع",
    myCards: "بطاقاتي",
    noSavedCards: "لا توجد بطاقة محفوظة.",
    default: "افتراضية",
    savedCardHint: "بطاقة محفوظة لحجوزاتك القادمة",
    paymentHistory: "سجل المدفوعات",
    noPayments: "لم يتم أي دفع بعد.",
    description: "الوصف",
    method: "الطريقة",
    date: "التاريخ",
    status: "الحالة",
    paidStatus: "ناجح",
    failedStatus: "فشل",
    refundedStatus: "مسترجع",
    cardType: "نوع البطاقة",
    lastFour: "آخر 4 أرقام",
    expiryPlaceholder: "تاريخ الانتهاء (مثال: 12/28)",
    cardHolder: "اسم صاحب البطاقة",
    saving: "جار الحفظ...",
    deleteCardConfirm: "حذف هذه البطاقة؟",
    docsTitle: "التذاكر والفواتير",
    docsSubtitle: "اطلع، اطبع وحمل وثائقك",
    confirmedTickets: "تذاكر مؤكدة",
    generatedInvoices: "فواتير منشأة",
    totalInvoiced: "إجمالي الفواتير",
    ticketsTab: "التذاكر",
    invoicesTab: "الفواتير",
    loadingDocuments: "جار تحميل الوثائق...",
    noTicket: "لا توجد تذكرة مؤكدة.",
    noInvoice: "لا توجد فاتورة متاحة.",
    ticket: "تذكرة",
    invoice: "فاتورة",
    paid: "مدفوع",
    profileAdmin: "ملف المدير",
    profileMine: "ملفي الشخصي",
    adminRole: "مدير",
    clientRole: "زبون SafarGo",
    editProfile: "تعديل الملف",
    managedOffers: "العروض المدارة",
    clientReservations: "حجوزات الزبناء",
    clients: "الزبناء",
    adminArea: "فضاء الإدارة",
    adminAreaText: "حسابك يسمح لك بتدبير العروض والزبناء والحجوزات.",
    openDashboard: "فتح لوحة التحكم",
    changePhoto: "تغيير الصورة",
    role: "الدور",
    phone: "الهاتف",
    deleteAccount: "حذف الحساب",
    deleteAccountConfirm: "حذف حسابك نهائيا؟",
    addPhotoError: "حدث خطأ أثناء إضافة الصورة",
    country: "البلد",
    changePassword: "تغيير كلمة المرور",
    oldPassword: "كلمة المرور القديمة",
    newPassword: "كلمة المرور الجديدة",
    paymentMethods: "وسائل الدفع",
    paymentMethodsText: "دبر بطاقاتك البنكية واطلع على سجل مدفوعاتك.",
    manageCards: "تدبير بطاقاتي",
    promo: "عرض",
    promoOmra: "عرض عمرة رمضان - تخفيض يصل إلى 15%",
    promoEvents: "تذاكر الفعاليات متاحة مع تأكيد سريع",
    promoShuttle: "حافلة الدار البيضاء - مراكش ابتداء من",
    promoHajj: "باقات الحج مع مرافقة كاملة",
    promoTransport: "عروض النقل: حافلة، طائرة، قطار وباخرة",
    catAll: "الكل",
    catTrips: "رحلات",
    catEvents: "فعاليات",
    catHajj: "حج",
    catOmra: "عمرة",
    catTransport: "نقل",
    catEurope: "أوروبا",
    catAsia: "آسيا",
    catAfrica: "إفريقيا",
    catAmericas: "الأمريكيتان",
    catMiddleEast: "الشرق الأوسط",
    catIndianOcean: "المحيط الهندي",
    transportAll: "الكل",
    plane: "طائرة",
    bus: "حافلة",
    train: "قطار",
    boat: "باخرة",
    car: "سيارة",
    accordingProgram: "حسب البرنامج",
    program: "البرنامج",
    adminLoginError: "تعذر تسجيل دخول المدير",
    adminAccess: "ولوج الإدارة",
    adminLogin: "تسجيل دخول المدير",
    loggedAsClient: "متصل كزبون",
    adminLoginHelp: "أدخل بيانات المدير للانتقال إلى لوحة التحكم.",
    adminEmail: "بريد المدير",
    adminPassword: "كلمة مرور المدير",
    checking: "جار التحقق...",
    enterAsAdmin: "الدخول كمدير",
    notFound: "الصفحة غير موجودة.",
    adminContent: "تدبير محتوى SafarGo",
    users: "المستخدمون",
    destinations: "الوجهات",
    addTrip: "إضافة رحلة",
    editTrip: "تعديل الرحلة",
    destination: "الوجهة",
    price: "السعر",
    duration: "المدة",
    actions: "الإجراءات",
    account: "الحساب",
    registeredAt: "تاريخ التسجيل",
    userRole: "مستخدم",
    active: "مفعل",
    inactive: "معطل",
    blocked: "محظور",
    removeAdmin: "إزالة المدير",
    makeAdmin: "جعله مديرا",
    client: "الزبون",
    editUser: "تعديل المستخدم",
    accountActive: "الحساب مفعل",
    offerType: "نوع العرض",
    photoGallery: "معرض الصور",
    imageUrlPerLine: "رابط صورة واحد في كل سطر",
    create: "إنشاء",
    confirmDelete: "تأكيد الحذف",
    deleteTripText: "هل تريد فعلا حذف هذه الرحلة؟ هذا الإجراء لا يمكن التراجع عنه.",
    deleteUser: "حذف المستخدم",
    deleteUserText: "هل تريد فعلا حذف هذا المستخدم؟ سيتم حذف حجوزاته ومدفوعاته وبطاقاته أيضا.",
    back: "رجوع",
    deleteReservation: "حذف الحجز",
  },
  en: {
    language: "Language",
    currency: "Currency",
    clientSpace: "CLIENT SPACE",
    adminSpace: "ADMINISTRATION",
    home: "Home",
    offers: "Offers",
    reservations: "Reservations",
    payment: "Payment",
    tickets: "Tickets",
    profile: "Profile",
    adminProfile: "Admin profile",
    dashboard: "Dashboard",
    logout: "Logout",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    confirm: "Confirm",
    print: "Print",
    download: "Download",
    requiredFields: "Please fill in all fields",
    fourDigitsRequired: "Please enter exactly 4 digits",
    addError: "Error while adding",
    updateError: "Error while updating",
    passwordMismatch: "Passwords do not match",
    passwordRule: "Password must contain at least 6 characters, one letter and one number",
    loginError: "Incorrect email or password",
    registerError: "Registration error",
    landingBadge: "SafarGo Travel",
    landingTitle: "Organized trips, Umrah, Hajj, events and transport",
    landingSubtitle: "Explore offers, compare prices and sign in to book in a few clicks.",
    login: "Login",
    signup: "Create account",
    mySpace: "My space",
    landingStatOffers: "organized offers",
    landingStatSupport: "local support",
    landingStatSecure: "secure booking",
    landingSelection: "SafarGo selection",
    popularOffers: "Popular offers",
    bookNow: "Book now",
    from: "from",
    authTagline: "Organized travel",
    authTitle: "Book your trips, tickets and packages in a few clicks.",
    authSubtitle: "SafarGo brings destinations, Umrah, Hajj, events and transport into one simple experience.",
    authOffers: "+25 offers",
    authSecure: "Secure payment",
    authSupport: "Local support",
    welcome: "Welcome",
    loginTitle: "Login",
    registerTitle: "Create account",
    loginHelp: "Sign in to manage your bookings.",
    registerHelp: "Create your SafarGo customer space.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    enterEmail: "Please enter your email",
    verificationCode: "Verification code",
    emailNotFound: "No account found with this email",
    invalidCode: "Incorrect code",
    enterNewPassword: "Please enter a new password",
    passwordUpdated: "Password updated successfully!",
    resetError: "Reset error",
    resetHero: "RESET YOUR PASSWORD",
    travelAgain: "AND TRAVEL AGAIN",
    yourEmail: "Your email",
    sending: "Sending...",
    sendCode: "Send code",
    codeSentTo: "Code sent to",
    verifyCode: "Verify code",
    reset: "Reset",
    backToLogin: "Back to login",
    signIn: "SIGN IN",
    signingIn: "SIGNING IN...",
    createAccount: "CREATE MY ACCOUNT",
    creatingAccount: "CREATING...",
    or: "OR",
    continueGoogle: "Continue with Google",
    continueApple: "Continue with Apple",
    continueMicrosoft: "Continue with Microsoft",
    fullName: "Full name",
    phoneOptional: "Phone (optional)",
    passwordRuleShort: "Password (letters + numbers)",
    confirmPassword: "Confirm password",
    hello: "Hello",
    homeSubtitle: "Welcome to SafarGo — ready for your next trip?",
    marketingTitle: "Discover the world with simple, fast booking",
    marketingSubtitle: "Trips, Umrah, Hajj, events and transport in one place.",
    exploreOffers: "Explore offers",
    confirmedTrips: "Confirmed trips",
    pending: "Pending",
    totalSpent: "Total spent",
    popularDestinations: "Popular destinations",
    seeAll: "See all",
    upcomingTrips: "Upcoming trips",
    noUpcomingTrips: "No trip scheduled.",
    quickAccess: "Quick access",
    exploreTrips: "Explore trips",
    myReservations: "My reservations",
    payments: "Payments",
    documents: "Tickets & invoices",
    myProfile: "My profile",
    departure: "Departure",
    passengers: "passenger(s)",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    offersTitle: "Trips & Offers",
    offersSubtitle: "Discover our best destinations",
    searchDestination: "Search a destination...",
    transportMode: "Transport mode",
    maxBudget: "Max budget",
    loadingOffers: "Loading offers...",
    noOffers: "No offer found.",
    seatsLeft: "spots left",
    perPerson: "/person",
    days: "days",
    bookOffer: "Book now",
    startingFrom: "Starting from",
    person: "per person",
    rating: "Rating",
    seats: "Spots",
    available: "available",
    transport: "Transport",
    nextDeparture: "Next departure",
    onRequest: "On request",
    route: "Route",
    eventDate: "Event date",
    continueBooking: "Continue booking",
    bookingFor: "Book",
    departureDate: "Departure date",
    passengerCount: "Number of passengers",
    total: "Total",
    inProgress: "In progress...",
    reservationSuccess: "Reservation created successfully!",
    reservationError: "Reservation error",
    reservationsTitle: "My Reservations",
    reservationsSubtitle: "Manage all your booked trips",
    newReservation: "+ New reservation",
    activeTotal: "Active total",
    all: "All",
    noReservation: "No reservation.",
    photos: "photos",
    pay: "Pay",
    cancelReservation: "Cancel",
    deleteReservationConfirm: "Delete this reservation permanently?",
    cancelReservationConfirm: "Cancel this reservation?",
    paymentSuccess: "Payment successful!",
    paymentError: "Payment error",
    payTitle: "Pay",
    amount: "Amount",
    noCardForPayment: "No saved card. Add one in Payments.",
    goToPayments: "Go to payments",
    chooseCard: "Choose a card",
    processing: "Processing...",
    confirmPayment: "Confirm payment",
    paymentsTitle: "Payments",
    paymentsSubtitle: "Manage your cards and view payment history",
    securePayment: "Secure payment",
    services: "Services",
    contact: "Contact",
    footerText: "SafarGo simplifies your trips, tickets, religious packages, events and transport with a clear, fast experience.",
    addCard: "Add card",
    savedCards: "Saved cards",
    successfulPayments: "Successful payments",
    totalPaid: "Total paid",
    myCards: "My cards",
    noSavedCards: "No saved card.",
    default: "Default",
    savedCardHint: "Card saved for your next bookings",
    paymentHistory: "Payment history",
    noPayments: "No payment made yet.",
    description: "Description",
    method: "Method",
    date: "Date",
    status: "Status",
    paidStatus: "Successful",
    failedStatus: "Failed",
    refundedStatus: "Refunded",
    cardType: "Card type",
    lastFour: "Last 4 digits",
    expiryPlaceholder: "Expiry date (e.g. 12/28)",
    cardHolder: "Card holder",
    saving: "Saving...",
    deleteCardConfirm: "Delete this card?",
    docsTitle: "Tickets & Invoices",
    docsSubtitle: "View, print and download your documents",
    confirmedTickets: "Confirmed tickets",
    generatedInvoices: "Generated invoices",
    totalInvoiced: "Total invoiced",
    ticketsTab: "Tickets",
    invoicesTab: "Invoices",
    loadingDocuments: "Loading documents...",
    noTicket: "No confirmed ticket.",
    noInvoice: "No invoice available.",
    ticket: "Ticket",
    invoice: "Invoice",
    paid: "PAID",
    profileAdmin: "Admin profile",
    profileMine: "My profile",
    adminRole: "Administrator",
    clientRole: "SafarGo customer",
    editProfile: "Edit profile",
    managedOffers: "Managed offers",
    clientReservations: "Customer reservations",
    clients: "Customers",
    adminArea: "Administrator space",
    adminAreaText: "Your account gives access to offers, customers and reservations management.",
    openDashboard: "Open dashboard",
    changePhoto: "Change photo",
    role: "Role",
    phone: "Phone",
    deleteAccount: "Delete account",
    deleteAccountConfirm: "Delete your account permanently?",
    addPhotoError: "Error while adding photo",
    country: "Country",
    changePassword: "Change password",
    oldPassword: "Old password",
    newPassword: "New password",
    paymentMethods: "Payment methods",
    paymentMethodsText: "Manage your bank cards and view your payment history.",
    manageCards: "Manage my cards",
    promo: "Promo",
    promoOmra: "Ramadan Umrah promotion - up to 15% off",
    promoEvents: "Event tickets available with fast confirmation",
    promoShuttle: "Casablanca - Marrakech shuttle from",
    promoHajj: "Hajj packages with full guidance",
    promoTransport: "Transport offers: bus, plane, train and ferry",
    catAll: "All",
    catTrips: "Trips",
    catEvents: "Events",
    catHajj: "Hajj",
    catOmra: "Umrah",
    catTransport: "Transport",
    catEurope: "Europe",
    catAsia: "Asia",
    catAfrica: "Africa",
    catAmericas: "Americas",
    catMiddleEast: "Middle East",
    catIndianOcean: "Indian Ocean",
    transportAll: "All",
    plane: "Plane",
    bus: "Bus",
    train: "Train",
    boat: "Boat",
    car: "Car",
    accordingProgram: "According to program",
    program: "Program",
    adminLoginError: "Admin login unavailable",
    adminAccess: "Administrator access",
    adminLogin: "Admin login",
    loggedAsClient: "Logged in as customer",
    adminLoginHelp: "Enter administrator credentials to switch to the admin dashboard.",
    adminEmail: "Admin email",
    adminPassword: "Admin password",
    checking: "Checking...",
    enterAsAdmin: "Enter as admin",
    notFound: "Page not found.",
    adminContent: "SafarGo content management",
    users: "Users",
    destinations: "Destinations",
    addTrip: "Add trip",
    editTrip: "Edit trip",
    destination: "Destination",
    price: "Price",
    duration: "Duration",
    actions: "Actions",
    account: "Account",
    registeredAt: "Registered on",
    userRole: "User",
    active: "Active",
    inactive: "Inactive",
    blocked: "Blocked",
    removeAdmin: "Remove admin",
    makeAdmin: "Make admin",
    client: "Customer",
    editUser: "Edit user",
    accountActive: "Account active",
    offerType: "Offer type",
    photoGallery: "Photo gallery",
    imageUrlPerLine: "One image URL per line",
    create: "Create",
    confirmDelete: "Confirm deletion",
    deleteTripText: "Do you really want to delete this trip? This action cannot be undone.",
    deleteUser: "Delete user",
    deleteUserText: "Do you really want to delete this user? Their reservations, payments and cards will also be deleted.",
    back: "Back",
    deleteReservation: "Delete reservation",
  },
};

const PreferencesContext = createContext<PreferencesContextType | null>(null);

export function PreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>((localStorage.getItem("language") as Language) || "fr");
  const [currency, setCurrency] = useState<Currency>((localStorage.getItem("currency") as Currency) || "EUR");

  useEffect(() => {
    document.body.classList.remove("dark");
    document.body.classList.add("light");
    localStorage.setItem("theme", "light");
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  useEffect(() => {
    localStorage.setItem("currency", currency);
  }, [currency]);

  const value = useMemo<PreferencesContextType>(() => ({
    language,
    currency,
    locale: language === "ar" ? "ar-MA" : language === "en" ? "en-US" : "fr-FR",
    setLanguage,
    setCurrency,
    formatMoney: (amountInEur: number) => {
      const value = currency === "MAD" ? amountInEur * EUR_TO_MAD : amountInEur;
      const locale = language === "ar" ? "ar-MA" : language === "en" ? "en-US" : "fr-FR";
      return new Intl.NumberFormat(locale, {
        maximumFractionDigits: 0,
      }).format(value) + (currency === "MAD" ? " DH" : " EUR");
    },
    formatDate: (date: string | number | Date, options?: Intl.DateTimeFormatOptions) => {
      const locale = language === "ar" ? "ar-MA" : language === "en" ? "en-US" : "fr-FR";
      return new Intl.DateTimeFormat(locale, options).format(new Date(date));
    },
    t: (key: string) => labels[language][key] || labels.fr[key] || key,
  }), [currency, language]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const ctx = useContext(PreferencesContext);
  if (!ctx) throw new Error("usePreferences must be used inside PreferencesProvider");
  return ctx;
}
